#!/bin/bash

ver_file="../src/Version.h"
temp_file="Version.h.tmp"

# create version file if missing
if [ ! -f $ver_file ]
then
	touch $ver_file
fi

# set fake version if not passed as parameter
if [ -z "$1" ]
then
	version="0.0.0"
else
	version="$1"
fi

# init values from git
git_branch=$(git rev-parse --abbrev-ref HEAD)
git_hash=$(git log -1 --format=%H)
git_shash=$(git log -1 --format=%h)
git_num=$(git rev-list HEAD --count)

# print data to version file
echo "// DO NOT EDIT THIS FILE - it's generated by update_version.sh and any change will be lo:qst" > $temp_file
echo "#define VERSION \"$version\"" >> $temp_file
echo "#define VERSION_BRANCH \"$git_branch\"" >> $temp_file
echo "#define VERSION_HASH \"$git_hash\"" >> $temp_file
echo "#define VERSION_NUM $git_num" >> $temp_file
echo "#define VERSION_SHORT_HASH \"$git_shash\"" >> $temp_file

# update version file if changed
files_diff=$(diff $ver_file $temp_file)

if [ -n "$files_diff" ]
then
	cp $temp_file $ver_file
fi

# remove temporary file
rm $temp_file
