#pragma once

namespace game
{

// NEW UNIT DIALOG
extern const char SpriteFileNewUnitDialog[];

enum SpriteIdNewUnitDialog : unsigned int
{
    // BACKGROUND
    IND_NU_DIALOG_BG_LEFT,
    IND_NU_DIALOG_BG_SLOT,
    IND_NU_DIALOG_BG_RIGHT,

    // BUILD BUTTON
    IND_NU_BUTTON_NORMAL,
    IND_NU_BUTTON_DISABLED,
    IND_NU_BUTTON_MOUSE_OVER,
    IND_NU_BUTTON_PUSHED,
    IND_NU_BUTTON_CHECKED,

    // PANELS
    IND_NU_PANEL_HEADERS,
    IND_NU_PANEL_UNIT,
    IND_NU_PANEL_STATS,

    // ICONS
    IND_NU_BAR_ITEM,
    IND_NU_ICON_ENERGY,
    IND_NU_ICON_MATERIAL,
    IND_NU_ICON_CLOSE,

    NUM_IND_NEW_UNIT_DIALOG
};

// OBJECT ACTION BUTTON
extern const char SpriteFileObjActionButton[];

enum SpriteIdObjActionButton : unsigned int
{
    // BUTTON
    IND_BUTTON_NORMAL,
    IND_BUTTON_DISABLED,
    IND_BUTTON_MOUSE_OVER,
    IND_BUTTON_PUSHED,
    IND_BUTTON_CHECKED,

    // ICONS
    IND_BUTTON_ICON_UNITS,
    IND_BUTTON_ICON_MOVE,
    IND_BUTTON_ICON_ATTACK,
    IND_BUTTON_ICON_CONQUER_CELL,
    IND_BUTTON_ICON_BUILD_WALL,
    IND_BUTTON_ICON_BUILD_STRUCT,
    IND_BUTTON_ICON_UPGRADE,
    IND_BUTTON_ICON_CANCEL,

    NUM_IND_OBJ_ACT_BUTTON
};


// MAIN MENU BUTTONS
extern const char SpriteFileMainMenu[];

enum SpriteIdMainMenu : unsigned int
{
    // PRIMARY BUTTON
    IND_MM_BTN1_NORMAL,
    IND_MM_BTN1_DISABLED,
    IND_MM_BTN1_OVER,
    IND_MM_BTN1_PUSHED,
    IND_MM_BTN1_CHECKED,

    // WISHLIST BUTTON
    IND_MM_BTNW_NORMAL,
    IND_MM_BTNW_OVER,
    IND_MM_BTNW_PUSHED,

    // SOCIAL BUTTON
    IND_MM_BTNS_NORMAL,
    IND_MM_BTNS_OVER,
    IND_MM_BTNS_PUSHED,

    // ICONS
    IND_MM_ICON_STEAM,
    IND_MM_ICON_DISCORD,
    IND_MM_ICON_TWITTER,
    IND_MM_ICON_YOUTUBE,
    IND_MM_ICON_LINKEDIN,

    NUM_MAIN_MENU_SPRITES
};

} // namespace game
